"""Regenerate docs/ai-index/SECTION-REGISTRY.md from curriculum data + content counts."""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
CONTENT = ROOT / "content"
OUT = ROOT / "docs" / "ai-index" / "SECTION-REGISTRY.md"

# slug → (content_type, cursor_rule, build_script, reference_page)
SECTION_META: dict[str, tuple[str, str, str, str]] = {
    "system-design": ("playbook", "system-design-posts.mdc", "—", "content/system-design/urlshortner.md"),
    "microservices": ("playbook", "microservices-posts.mdc", "—", "content/microservices/circuit-breaker-pattern.md"),
    "technology-playbook": ("playbook", "—", "generate_technology_playbook.py", "content/technology-playbook/_index.md"),
    "java-engineering": ("cheat-sheet", "java-cheatsheet-posts.mdc", "build_java_engineering_handbook.py", "content/java-engineering/hashmap-internals.md"),
    "spring-boot": ("cheat-sheet", "spring-boot-handbook-posts.mdc", "build_spring_boot_handbook.py", "content/spring-boot/_index.md"),
    "python-cheatsheet": ("cheat-sheet", "cheatsheet-template.mdc", "build_python_cheatsheet_handbook.py", "content/python-cheatsheet/_index.md"),
    "golang-cheatsheet": ("cheat-sheet", "cheatsheet-template.mdc", "build_golang_cheatsheet.py", "content/golang-cheatsheet/_index.md"),
    "kafka-handbook": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "—", "content/kafka-handbook/_index.md"),
    "kubernetes-handbook": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "build_kubernetes_cheatsheet.py", "content/kubernetes-handbook/kubernetes.md"),
    "redis-cheatsheet": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "build_redis_cheatsheet.py", "content/redis-cheatsheet/_index.md"),
    "database-handbook": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "—", "content/database-handbook/_index.md"),
    "postgresql-cheatsheet": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "build_postgresql_cheatsheet.py", "content/postgresql-cheatsheet/_index.md"),
    "mongodb-cheatsheet": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "—", "content/mongodb-cheatsheet/_index.md"),
    "cloud-handbook": ("cheat-sheet", "engineering-handbook-cheatsheets.mdc", "—", "content/cloud-handbook/_index.md"),
    "design-patterns": ("interview-LLD", "lld-posts.mdc", "generate_lld_stubs.py", "content/design-patterns/strategy-pattern.md"),
    "dsa-coding": ("interview-DSA", "dsa-coding-posts.mdc", "build_dsa_coding_handbook.py", "content/dsa-coding/01-arrays-hashmap-two-pointers/two-sum.md"),
    "interview-prep": ("interview-QA", "—", "—", "content/interview-prep/_index.md"),
    "ai-for-engineers": ("career", "—", "—", "content/ai-for-engineers/_index.md"),
    "security-architecture": ("playbook", "—", "—", "content/security-architecture/_index.md"),
}


def load_yaml(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def count_pages(slug: str) -> int:
    section_dir = CONTENT / slug
    if not section_dir.is_dir():
        return 0
    return sum(1 for _ in section_dir.rglob("*.md"))


def module_count(slug: str, sidebar: dict) -> str:
    cfg = sidebar.get("sections", {}).get(slug, {})
    mod_key = cfg.get("modules")
    if not mod_key:
        return "—"
    mod_path = DATA / f"{mod_key}.yaml"
    if not mod_path.exists():
        return "?"
    mods = load_yaml(mod_path).get("modules", [])
    return str(len(mods))


def topic_count(slug: str, sidebar: dict) -> str:
    cfg = sidebar.get("sections", {}).get(slug, {})
    order_key = cfg.get("order")
    if not order_key:
        return "—"
    order_path = DATA / f"{order_key}.yaml"
    if not order_path.exists():
        return "?"
    topics = load_yaml(order_path).get("topics", [])
    return str(len(topics))


def main() -> None:
    curriculum = load_yaml(DATA / "curriculum_sections.yaml")
    sidebar = load_yaml(DATA / "curriculum_sidebar.yaml")
    groups = {g["id"]: g["label"] for g in curriculum.get("groups", [])}

    lines = [
        "# Section Registry",
        "",
        "> Auto-generated by `scripts/generate_ai_index.py`. Do not edit by hand.",
        "> Regenerate: `python scripts/generate_ai_index.py`",
        "",
        "Canonical map of all curriculum sections. Use this instead of scanning `content/`.",
        "",
        "## Summary Table",
        "",
        "| Slug | Group | Pages | Modules | Topics (order) | Type | Cursor rule | Build script |",
        "|------|-------|------:|--------:|---------------:|------|-------------|--------------|",
    ]

    for sec in curriculum.get("sections", []):
        slug = sec["slug"]
        group = groups.get(sec.get("group", ""), sec.get("group", ""))
        pages = count_pages(slug)
        mods = module_count(slug, sidebar)
        topics = topic_count(slug, sidebar)
        meta = SECTION_META.get(slug, ("—", "—", "—", "—"))
        ctype, rule, build, _ref = meta
        lines.append(
            f"| `{slug}` | {group} | {pages} | {mods} | {topics} | {ctype} | `{rule}` | `{build}` |"
        )

    lines.extend(["", "## Per-Section Detail", ""])

    for sec in curriculum.get("sections", []):
        slug = sec["slug"]
        cfg = sidebar.get("sections", {}).get(slug, {})
        meta = SECTION_META.get(slug, ("—", "—", "—", f"content/{slug}/_index.md"))
        ctype, rule, build, ref = meta

        lines.append(f"### `{slug}`")
        lines.append("")
        lines.append(f"- **Menu label:** {sec.get('menuLabel', slug)}")
        lines.append(f"- **Group:** {sec.get('group', '—')}")
        lines.append(f"- **Content path:** `content/{slug}/`")
        lines.append(f"- **Pages:** {count_pages(slug)}")
        if cfg.get("modules"):
            lines.append(f"- **Modules data:** `data/{cfg['modules']}.yaml`")
        if cfg.get("order"):
            lines.append(f"- **Order data:** `data/{cfg['order']}.yaml`")
        lines.append(f"- **Layouts:** `layouts/{slug}/list.html`, `layouts/{slug}/single.html`")
        lines.append(f"- **Content type:** {ctype}")
        lines.append(f"- **Cursor rule:** `.cursor/rules/{rule}`")
        lines.append(f"- **Build script:** `scripts/{build}`" if build != "—" else "- **Build script:** hand-maintained")
        lines.append(f"- **Reference page:** `{ref}`")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(curriculum.get('sections', []))} sections)")


if __name__ == "__main__":
    main()
