"""Top 150 Go interview questions — (question, difficulty, level, topic, deep_dive_path)."""
from __future__ import annotations

# Distribution: Internals 40 | Concurrency 30 | Performance 25 | Troubleshooting 20 | Production 15 | Core/Testing 20

QUESTIONS: list[tuple[str, str, str, str, str]] = [
    # --- Internals & Runtime (1-40) ---
    ("What are the main components of the Go runtime and how do they interact at process startup?", "Hard", "Architect", "Runtime", "03-go-internals/go-runtime.md"),
    ("How does the Go linker differ from a traditional dynamic linker in terms of deployment artifacts?", "Medium", "Architect", "Runtime", "03-go-internals/go-runtime.md"),
    ("Explain the GMP scheduler model — what role does each of G, M, and P play?", "Hard", "Senior Engineer", "Scheduler", "03-go-internals/scheduler.md"),
    ("What is work stealing in the Go scheduler and when does it occur?", "Hard", "Lead", "Scheduler", "03-go-internals/scheduler.md"),
    ("How did goroutine preemption change from Go 1.13 to Go 1.14+ and why does it matter?", "Hard", "Architect", "Scheduler", "03-go-internals/scheduler.md"),
    ("What happens when a goroutine blocks on a syscall — how is the M released?", "Hard", "Lead", "Scheduler", "03-go-internals/scheduler.md"),
    ("How does GOMAXPROCS affect parallelism versus concurrency in a CPU-bound service?", "Medium", "Senior Engineer", "Scheduler", "03-go-internals/scheduler.md"),
    ("What is the netpoller and how does it integrate with channel and network I/O blocking?", "Hard", "Architect", "Scheduler", "03-go-internals/scheduler.md"),
    ("Why do goroutine stacks start small and grow — what are the tradeoffs?", "Medium", "Senior Engineer", "Scheduler", "03-go-internals/scheduler.md"),
    ("What is a local run queue versus the global run queue in the scheduler?", "Hard", "Lead", "Scheduler", "03-go-internals/scheduler.md"),
    ("Define happens-before in the Go memory model and list three sources of edges.", "Medium", "Senior Engineer", "Memory Model", "03-go-internals/memory-model.md"),
    ("Why is a data race undefined behavior even if the observed result seems consistent?", "Medium", "Senior Engineer", "Memory Model", "03-go-internals/memory-model.md"),
    ("How do channel send/receive operations establish happens-before relationships?", "Medium", "Lead", "Memory Model", "03-go-internals/memory-model.md"),
    ("When should you use sync/atomic versus a mutex for a simple counter?", "Medium", "Senior Engineer", "Memory Model", "03-go-internals/memory-model.md"),
    ("What guarantees does sync.Once provide and how does it relate to happens-before?", "Medium", "Senior Engineer", "Memory Model", "03-go-internals/memory-model.md"),
    ("Describe the tri-color concurrent mark-sweep GC algorithm at a high level.", "Hard", "Lead", "GC", "03-go-internals/garbage-collection.md"),
    ("How does GOGC control GC frequency and what is the default behavior?", "Medium", "Senior Engineer", "GC", "03-go-internals/garbage-collection.md"),
    ("What are STW phases in Go GC and how have pause times trended over releases?", "Hard", "Architect", "GC", "03-go-internals/garbage-collection.md"),
    ("Why is allocation rate often more important than live heap size for GC latency?", "Hard", "Lead", "GC", "03-go-internals/garbage-collection.md"),
    ("What is a write barrier in Go's GC and when does it apply?", "Hard", "Architect", "GC", "03-go-internals/garbage-collection.md"),
    ("Why should you avoid runtime.SetFinalizer for resource cleanup?", "Medium", "Senior Engineer", "GC", "03-go-internals/garbage-collection.md"),
    ("What does uintptr not being a GC root mean in practice?", "Medium", "Lead", "GC", "03-go-internals/garbage-collection.md"),
    ("How do you interpret GODEBUG=gctrace=1 output during a latency incident?", "Hard", "Lead", "GC", "03-go-internals/garbage-collection.md"),
    ("What is escape analysis and who performs it in the Go toolchain?", "Medium", "Senior Engineer", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("Give examples of code patterns that force a variable to escape to the heap.", "Medium", "Senior Engineer", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("How do you use go build -gcflags=-m to inspect escape decisions?", "Medium", "Senior Engineer", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("When does returning a pointer to a local variable remain stack-safe?", "Hard", "Lead", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("How does closure capture affect escape analysis?", "Hard", "Lead", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("What performance impact does heap allocation have beyond GC — cache locality, etc.?", "Medium", "Senior Engineer", "Escape Analysis", "03-go-internals/escape-analysis.md"),
    ("How is a reflect.Value constructed and when must the value be addressable to Set?", "Medium", "Senior Engineer", "Reflection", "03-go-internals/reflection.md"),
    ("What is the cost of reflection on a hot path and mitigations?", "Medium", "Lead", "Reflection", "03-go-internals/reflection.md"),
    ("When would you choose generics over reflection in Go 1.18+?", "Medium", "Senior Engineer", "Reflection", "03-go-internals/reflection.md"),
    ("How does reflect.DeepEqual differ from == for slices and maps?", "Easy", "Senior Engineer", "Reflection", "03-go-internals/reflection.md"),
    ("What breaks silently when refactoring struct fields accessed via reflection?", "Medium", "Lead", "Reflection", "03-go-internals/reflection.md"),
    ("How does the Go compiler represent interface values internally (type, data)?", "Hard", "Architect", "Interfaces", "02-core-go/interfaces.md"),
    ("What is the difference between nil interface and interface holding typed nil?", "Medium", "Senior Engineer", "Interfaces", "02-core-go/interfaces.md"),
    ("How do value versus pointer receivers affect interface satisfaction?", "Medium", "Senior Engineer", "Methods", "01-fundamentals/methods.md"),
    ("What is the size cost of an interface{} holding a small value versus a pointer?", "Hard", "Architect", "Interfaces", "02-core-go/interfaces.md"),
    ("How does the runtime handle stack growth during deep recursion?", "Hard", "Lead", "Scheduler", "03-go-internals/scheduler.md"),
    # --- Concurrency (41-70) ---
    ("What is the difference between concurrency and parallelism in Go services?", "Easy", "Senior Engineer", "Goroutines", "04-concurrency/goroutines.md"),
    ("How can unbounded goroutine creation cause production incidents?", "Medium", "Lead", "Goroutines", "04-concurrency/goroutines.md"),
    ("What happens to child goroutines when main returns without synchronization?", "Easy", "Senior Engineer", "Goroutines", "04-concurrency/goroutines.md"),
    ("How should errors from goroutines propagate to the caller?", "Medium", "Senior Engineer", "Goroutines", "04-concurrency/goroutines.md"),
    ("Why does panic in a goroutine crash the whole process unless recovered?", "Medium", "Senior Engineer", "Goroutines", "04-concurrency/goroutines.md"),
    ("What is the difference between buffered and unbuffered channels semantically?", "Medium", "Senior Engineer", "Channels", "04-concurrency/channels.md"),
    ("Who should close a channel and what happens on send to a closed channel?", "Medium", "Senior Engineer", "Channels", "04-concurrency/channels.md"),
    ("Why is a nil channel useful inside select?", "Medium", "Senior Engineer", "Select", "04-concurrency/select.md"),
    ("How does select choose among multiple ready cases?", "Medium", "Senior Engineer", "Select", "04-concurrency/select.md"),
    ("What is the risk of select with only default in a tight loop?", "Medium", "Lead", "Select", "04-concurrency/select.md"),
    ("How do you implement timeouts without leaking goroutines?", "Hard", "Lead", "Select", "04-concurrency/select.md"),
    ("What are the rules for context.Context cancellation propagation?", "Medium", "Senior Engineer", "Context", "04-concurrency/context.md"),
    ("Why should context be the first function parameter and not stored in structs?", "Medium", "Lead", "Context", "04-concurrency/context.md"),
    ("When is context.WithValue appropriate versus anti-pattern?", "Medium", "Lead", "Context", "04-concurrency/context.md"),
    ("What error does ctx.Err() return for deadline versus cancel?", "Easy", "Senior Engineer", "Context", "04-concurrency/context.md"),
    ("When is sync.Mutex preferable to a channel for protecting shared state?", "Medium", "Senior Engineer", "Mutex", "04-concurrency/mutex.md"),
    ("How does lock ordering prevent deadlocks in nested critical sections?", "Hard", "Lead", "Mutex", "04-concurrency/mutex.md"),
    ("Why must sync.Mutex not be copied after first use?", "Medium", "Senior Engineer", "Mutex", "04-concurrency/mutex.md"),
    ("When does sync.RWMutex outperform Mutex and when is it slower?", "Medium", "Senior Engineer", "RWMutex", "04-concurrency/rwmutex.md"),
    ("What is writer starvation in RWMutex and is it a practical concern?", "Hard", "Lead", "RWMutex", "04-concurrency/rwmutex.md"),
    ("What are the correct WaitGroup usage rules (Add before go, no copy)?", "Medium", "Senior Engineer", "Sync", "04-concurrency/sync-package.md"),
    ("When should you use sync.Pool and what state must you reset on Get?", "Medium", "Senior Engineer", "Sync", "04-concurrency/sync-package.md"),
    ("When is sync.Map appropriate versus mutex plus map?", "Hard", "Lead", "Sync", "04-concurrency/sync-package.md"),
    ("How do you implement a worker pool with bounded concurrency?", "Medium", "Senior Engineer", "Patterns", "04-concurrency/concurrency-patterns.md"),
    ("Explain fan-out fan-in and a failure mode if a stage blocks.", "Hard", "Lead", "Patterns", "04-concurrency/concurrency-patterns.md"),
    ("How do pipelines compose channels and where does backpressure belong?", "Hard", "Architect", "Patterns", "04-concurrency/concurrency-patterns.md"),
    ("How do you cancel a pipeline of goroutines cleanly using context?", "Hard", "Lead", "Patterns", "04-concurrency/concurrency-patterns.md"),
    ("What is the share-memory-by-communicating idiom and its limits?", "Medium", "Architect", "Patterns", "04-concurrency/concurrency-patterns.md"),
    ("How do you detect goroutine leaks in a long-running HTTP service?", "Hard", "Lead", "Goroutines", "04-concurrency/goroutines.md"),
    ("What is a semaphore pattern using buffered channels versus sync.Mutex?", "Medium", "Senior Engineer", "Patterns", "04-concurrency/concurrency-patterns.md"),
    # --- Performance (71-95) ---
    ("What are the first three steps you take when a Go service misses latency SLO?", "Medium", "Lead", "Profiling", "05-performance/profiling.md"),
    ("How do you capture a CPU profile from a production process safely?", "Hard", "Lead", "Profiling", "05-performance/profiling.md"),
    ("What does a flat versus cum column mean in pprof CPU output?", "Medium", "Senior Engineer", "Profiling", "05-performance/profiling.md"),
    ("How do you distinguish alloc_objects from inuse_space in heap profiles?", "Hard", "Senior Engineer", "Profiling", "05-performance/profiling.md"),
    ("When would you use goroutine profile versus trace?", "Hard", "Lead", "Profiling", "05-performance/profiling.md"),
    ("How does runtime/trace help diagnose scheduler latency?", "Hard", "Architect", "Profiling", "05-performance/profiling.md"),
    ("What is benchstat and how do you compare two benchmark runs?", "Medium", "Senior Engineer", "Benchmarking", "05-performance/benchmarking.md"),
    ("Why use b.ReportAllocs() and what does allocs/op indicate?", "Medium", "Senior Engineer", "Benchmarking", "05-performance/benchmarking.md"),
    ("How do you reduce benchmark noise on shared CI runners?", "Medium", "Lead", "Benchmarking", "05-performance/benchmarking.md"),
    ("What mistakes make micro-benchmarks misleading for production?", "Medium", "Lead", "Benchmarking", "05-performance/benchmarking.md"),
    ("List three allocation-reduction tactics for hot HTTP handlers.", "Medium", "Senior Engineer", "Optimization", "05-performance/performance-optimization.md"),
    ("When is sync.Pool the wrong tool for object reuse?", "Hard", "Lead", "Optimization", "05-performance/performance-optimization.md"),
    ("How does preallocating slices with make([]T, 0, n) reduce GC pressure?", "Easy", "Senior Engineer", "Memory", "05-performance/memory-optimization.md"),
    ("How can struct field ordering affect memory padding and cache lines?", "Hard", "Architect", "Memory", "05-performance/memory-optimization.md"),
    ("When should you prefer value semantics over pointers for small structs?", "Medium", "Senior Engineer", "Memory", "05-performance/memory-optimization.md"),
    ("How do string conversions from []byte cause allocations and how to avoid?", "Medium", "Senior Engineer", "Optimization", "05-performance/performance-optimization.md"),
    ("What is the cost of defer in tight loops — myth versus reality?", "Medium", "Senior Engineer", "Optimization", "05-performance/performance-optimization.md"),
    ("How do you profile mutex contention with block profile?", "Hard", "Lead", "Profiling", "05-performance/profiling.md"),
    ("What GOMAXPROCS setting is appropriate for container CPU limits?", "Hard", "Architect", "Scheduler", "03-go-internals/scheduler.md"),
    ("How would you tune GOGC for a latency-sensitive versus batch workload?", "Hard", "Architect", "GC", "03-go-internals/garbage-collection.md"),
    ("When is forcing runtime.GC() ever justified in production?", "Easy", "Senior Engineer", "GC", "03-go-internals/garbage-collection.md"),
    ("How do you find allocation hotspots from pprof allocs profile?", "Medium", "Senior Engineer", "Profiling", "05-performance/profiling.md"),
    ("What is the impact of excessive interface boxing on allocations?", "Hard", "Lead", "Optimization", "05-performance/performance-optimization.md"),
    ("How do you benchmark concurrent code without data races?", "Hard", "Lead", "Benchmarking", "05-performance/benchmarking.md"),
    ("What strategies reduce lock contention in read-heavy caches?", "Medium", "Lead", "Optimization", "05-performance/performance-optimization.md"),
    # --- Troubleshooting (96-115) ---
    ("How do you triage a sudden spike in goroutine count from /debug/pprof/goroutine?", "Hard", "Lead", "Troubleshooting", "05-performance/profiling.md"),
    ("What stack patterns indicate a goroutine blocked on channel receive forever?", "Hard", "Senior Engineer", "Troubleshooting", "04-concurrency/channels.md"),
    ("How do you debug a deadlock involving sync.Mutex lock ordering?", "Hard", "Lead", "Troubleshooting", "04-concurrency/mutex.md"),
    ("What does go test -race output tell you and what are false-positive pitfalls?", "Medium", "Senior Engineer", "Troubleshooting", "07-testing/testing.md"),
    ("How do you interpret a panic stack trace with multiple goroutines?", "Medium", "Senior Engineer", "Troubleshooting", "04-concurrency/goroutines.md"),
    ("What causes 'fatal error: all goroutines are asleep - deadlock!'?", "Medium", "Senior Engineer", "Troubleshooting", "04-concurrency/channels.md"),
    ("How do you diagnose memory leaks that are actually slice backing-array retention?", "Hard", "Lead", "Troubleshooting", "01-fundamentals/slices.md"),
    ("What symptoms distinguish GC thrashing from CPU-bound slowness?", "Hard", "Lead", "Troubleshooting", "03-go-internals/garbage-collection.md"),
    ("How do you find which HTTP handler allocates the most per request?", "Medium", "Senior Engineer", "Troubleshooting", "05-performance/profiling.md"),
    ("What runbook steps apply when OOMKilled in Kubernetes for a Go pod?", "Hard", "Architect", "Troubleshooting", "05-performance/memory-optimization.md"),
    ("How do context deadline exceeded storms appear in logs and metrics?", "Medium", "Lead", "Troubleshooting", "04-concurrency/context.md"),
    ("What causes select fair starvation and how do you reproduce it?", "Hard", "Architect", "Troubleshooting", "04-concurrency/select.md"),
    ("How do you debug a production issue only reproducible under -race?", "Hard", "Lead", "Troubleshooting", "03-go-internals/memory-model.md"),
    ("What is the fix for WaitGroup misuse that panics with negative counter?", "Easy", "Senior Engineer", "Troubleshooting", "04-concurrency/sync-package.md"),
    ("How do you trace a request ID through logs when middleware order is wrong?", "Medium", "Lead", "Troubleshooting", "06-production-go/logging.md"),
    ("What indicates interface nil comparison bugs in JSON API responses?", "Medium", "Senior Engineer", "Troubleshooting", "02-core-go/interfaces.md"),
    ("How do you validate a fix for a goroutine leak with load testing?", "Hard", "Lead", "Troubleshooting", "04-concurrency/goroutines.md"),
    ("What pprof signs suggest mutex contention as the bottleneck?", "Hard", "Senior Engineer", "Troubleshooting", "05-performance/profiling.md"),
    ("How do map concurrent write panics manifest and what is the permanent fix?", "Medium", "Senior Engineer", "Troubleshooting", "01-fundamentals/maps.md"),
    ("What is your first-hour checklist for a Go service latency regression after deploy?", "Hard", "Architect", "Troubleshooting", "06-production-go/production-checklists.md"),
    # --- Production Engineering (116-130) ---
    ("What fields belong in structured production logs for a REST API?", "Medium", "Lead", "Logging", "06-production-go/logging.md"),
    ("How do you propagate trace and span IDs from OpenTelemetry into logs?", "Hard", "Lead", "Observability", "06-production-go/observability.md"),
    ("What metrics would you expose from a standard Go HTTP server?", "Medium", "Senior Engineer", "Observability", "06-production-go/observability.md"),
    ("How do you configure RED versus USE metrics for Go microservices?", "Hard", "Architect", "Observability", "06-production-go/observability.md"),
    ("What is the recommended pattern for loading config from env versus files?", "Medium", "Senior Engineer", "Config", "06-production-go/configuration-management.md"),
    ("How do you avoid committing secrets while using environment variables?", "Medium", "Lead", "Config", "06-production-go/configuration-management.md"),
    ("Describe graceful shutdown for net/http.Server on SIGTERM in Kubernetes.", "Hard", "Lead", "Shutdown", "06-production-go/graceful-shutdown.md"),
    ("How long should Shutdown context timeout be relative to pod terminationGracePeriodSeconds?", "Hard", "Architect", "Shutdown", "06-production-go/graceful-shutdown.md"),
    ("What resources must be closed on shutdown besides HTTP listeners?", "Medium", "Senior Engineer", "Shutdown", "06-production-go/graceful-shutdown.md"),
    ("What belongs on a Go service production readiness checklist?", "Medium", "Lead", "Checklists", "06-production-go/production-checklists.md"),
    ("When do you run go vet, staticcheck, and -race in CI pipelines?", "Easy", "Senior Engineer", "Checklists", "06-production-go/production-checklists.md"),
    ("How do you version Go in go.mod and Docker images consistently?", "Medium", "Lead", "Modules", "02-core-go/go-modules.md"),
    ("What is the policy for retract directives after publishing a bad module version?", "Medium", "Lead", "Modules", "02-core-go/go-modules.md"),
    ("How do you handle private module fetch in CI without GOPATH hacks?", "Medium", "Senior Engineer", "Dependencies", "02-core-go/dependency-management.md"),
    ("What alerting rules catch goroutine leaks before OOM?", "Hard", "Architect", "Observability", "06-production-go/observability.md"),
    # --- Core Go & Testing (131-150) ---
    ("Why does append sometimes mutate a shared backing array?", "Medium", "Senior Engineer", "Slices", "01-fundamentals/slices.md"),
    ("What is the difference between nil slice and empty slice for JSON encoding?", "Easy", "Senior Engineer", "Slices", "01-fundamentals/slices.md"),
    ("Why can't you take the address of a map element?", "Medium", "Senior Engineer", "Maps", "01-fundamentals/maps.md"),
    ("How does errors.Is differ from == for wrapped errors?", "Medium", "Senior Engineer", "Errors", "02-core-go/error-handling.md"),
    ("When should you use errors.As versus a type switch on error?", "Medium", "Senior Engineer", "Errors", "02-core-go/error-handling.md"),
    ("What is the anti-pattern of logging and returning the same error?", "Easy", "Senior Engineer", "Errors", "02-core-go/error-handling.md"),
    ("How does table-driven testing scale to many edge cases?", "Easy", "Senior Engineer", "Testing", "07-testing/testing.md"),
    ("Why is t.Fatal unsafe inside a goroutine in tests?", "Medium", "Senior Engineer", "Testing", "07-testing/testing.md"),
    ("How do you structure integration tests with build tags?", "Medium", "Lead", "Testing", "07-testing/test-strategies.md"),
    ("When do you use interface mocks versus fakes in Go tests?", "Medium", "Lead", "Mocking", "07-testing/mocking.md"),
    ("What tools generate mocks from interfaces and tradeoffs?", "Medium", "Senior Engineer", "Mocking", "07-testing/mocking.md"),
    ("How do you test concurrent code deterministically?", "Hard", "Lead", "Testing", "07-testing/test-strategies.md"),
    ("What is the package layout convention for cmd, internal, and pkg?", "Medium", "Senior Engineer", "Packages", "02-core-go/packages.md"),
    ("How does Minimal Version Selection resolve conflicting module requirements?", "Hard", "Architect", "Dependencies", "02-core-go/dependency-management.md"),
    ("When is vendoring required for reproducible builds?", "Medium", "Lead", "Dependencies", "02-core-go/dependency-management.md"),
    ("How do init() functions complicate testing and what is the mitigation?", "Medium", "Senior Engineer", "Packages", "02-core-go/packages.md"),
    ("What compile-time check ensures a type satisfies an interface?", "Easy", "Senior Engineer", "Interfaces", "02-core-go/interfaces.md"),
    ("How does embedding promote methods and what happens with nil embedded pointers?", "Medium", "Senior Engineer", "Structs", "01-fundamentals/structs.md"),
    ("What changed in Go 1.22 loop variable capture semantics?", "Medium", "Senior Engineer", "Functions", "01-fundamentals/functions.md"),
    ("How would you design error types for a multi-tenant API with retry hints?", "Hard", "Architect", "Errors", "02-core-go/error-handling.md"),
    ("What is the difference between comparable and copyable types in Go generics constraints?", "Hard", "Architect", "Core Go", "02-core-go/interfaces.md"),
]

assert len(QUESTIONS) == 150, len(QUESTIONS)
