"""Top 150 MongoDB interview questions — shared data."""

QUESTIONS = [
    # Architecture (40) — 1-40
    (1, "When would you choose MongoDB's document model over a relational database for a greenfield product?", "Medium", "Architect", "Architecture", "02-core-mongodb/schema-design.md"),
    (2, "How does embedding data change read latency versus normalizing into multiple collections?", "Medium", "Senior Engineer", "Architecture", "02-core-mongodb/schema-design.md"),
    (3, "What access-pattern mistakes force expensive scatter-gather queries on a sharded cluster?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (4, "How do mongod, mongos, and config servers divide responsibility in a sharded deployment?", "Medium", "Senior Engineer", "Architecture", "02-core-mongodb/architecture.md"),
    (5, "Why is a standalone mongod unsuitable for production high availability?", "Easy", "Senior Engineer", "Architecture", "02-core-mongodb/architecture.md"),
    (6, "How does the 16 MB document limit influence schema design for comment threads or event streams?", "Medium", "Lead", "Architecture", "02-core-mongodb/schema-design.md"),
    (7, "When is the bucketing pattern preferable to unbounded embedded arrays?", "Medium", "Senior Engineer", "Architecture", "02-core-mongodb/schema-design.md"),
    (8, "How do schema design and shard key selection interact in a multi-tenant SaaS platform?", "Hard", "Architect", "Architecture", "02-core-mongodb/schema-design.md"),
    (9, "What deployment topology would you propose for read-heavy analytics alongside write-heavy OLTP?", "Hard", "Architect", "Architecture", "02-core-mongodb/replication.md"),
    (10, "How do change streams fit into event-driven architectures compared to polling?", "Medium", "Lead", "Architecture", "02-core-mongodb/replication.md"),
    (11, "When should time series collections replace hand-rolled bucketing schemas?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/collections.md"),
    (12, "What is the tradeoff between JSON Schema validation at write time versus application-only validation?", "Medium", "Lead", "Architecture", "01-fundamentals/collections.md"),
    (13, "How would you model a product catalog with variants that differ wildly in attributes?", "Hard", "Architect", "Architecture", "02-core-mongodb/schema-design.md"),
    (14, "When does `$lookup` indicate a schema modeling problem rather than a query problem?", "Medium", "Senior Engineer", "Architecture", "03-query-performance/aggregation-pipeline.md"),
    (15, "How do multi-document transactions change oplog volume and replication lag characteristics?", "Hard", "Lead", "Architecture", "02-core-mongodb/transactions.md"),
    (16, "What signals indicate a workload has outgrown a single replica set before ops teams admit it?", "Hard", "Architect", "Architecture", "04-production-operations/capacity-planning.md"),
    (17, "How does zone sharding support data residency requirements across regions?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (18, "When is hashed versus ranged shard key correct for an order ID domain?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (19, "How would you design Atlas Global Cluster reads for users geographically distributed?", "Hard", "Architect", "Architecture", "01-fundamentals/atlas-basics.md"),
    (20, "What CQRS patterns pair naturally with MongoDB as a read model store?", "Medium", "Architect", "Architecture", "02-core-mongodb/schema-design.md"),
    (21, "How do views differ architecturally from materialized aggregation results?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/collections.md"),
    (22, "What polymorphism strategies avoid unmanageable index sprawl on event collections?", "Hard", "Lead", "Architecture", "02-core-mongodb/schema-design.md"),
    (23, "How does co-locating related data by shard key reduce cross-shard `$lookup` cost?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (24, "When would you split one logical domain across multiple MongoDB databases?", "Medium", "Lead", "Architecture", "02-core-mongodb/architecture.md"),
    (25, "How do extended reference patterns balance embed and reference tradeoffs?", "Medium", "Senior Engineer", "Architecture", "02-core-mongodb/schema-design.md"),
    (26, "What architect-level risks exist when using MongoDB as a system of record for financial balances?", "Hard", "Architect", "Architecture", "02-core-mongodb/transactions.md"),
    (27, "How does Atlas Data Federation change analytics architecture without ETL batch windows?", "Medium", "Architect", "Architecture", "01-fundamentals/atlas-basics.md"),
    (28, "When is GridFS still justified versus object storage for large blobs?", "Medium", "Lead", "Architecture", "01-fundamentals/documents.md"),
    (29, "How would you blueprint shard count and replica set size in an ADR for a 3-year growth plan?", "Hard", "Architect", "Architecture", "04-production-operations/capacity-planning.md"),
    (30, "What coupling appears when microservices share one MongoDB database versus database-per-service?", "Hard", "Architect", "Architecture", "02-core-mongodb/architecture.md"),
    (31, "How do collation choices at index creation affect case-insensitive search architecture?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/collections.md"),
    (32, "When does Atlas Serverless beat fixed-tier clusters for spiky workloads?", "Medium", "Architect", "Architecture", "01-fundamentals/atlas-basics.md"),
    (33, "How would you isolate noisy-neighbor tenants on a shared sharded cluster?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (34, "What read routing architecture uses secondaryPreferred without violating freshness SLAs?", "Hard", "Lead", "Architecture", "02-core-mongodb/replication.md"),
    (35, "How do unique indexes on sharded collections constrain schema evolution?", "Hard", "Architect", "Architecture", "02-core-mongodb/sharding.md"),
    (36, "When is dual-writing to MongoDB and PostgreSQL worth the complexity?", "Hard", "Architect", "Architecture", "05-comparisons/mongodb-vs-postgresql.md"),
    (37, "How does document model versioning interact with blue/green application deploys?", "Medium", "Lead", "Architecture", "02-core-mongodb/schema-design.md"),
    (38, "What platform capabilities would push you toward Couchbase over MongoDB?", "Medium", "Architect", "Architecture", "05-comparisons/mongodb-vs-couchbase.md"),
    (39, "When does Cassandra beat MongoDB for time-series ingestion at billion-events scale?", "Hard", "Architect", "Architecture", "05-comparisons/mongodb-vs-cassandra.md"),
    (40, "How would you present MongoDB versus PostgreSQL tradeoffs in a architecture review board?", "Medium", "Architect", "Architecture", "05-comparisons/mongodb-vs-postgresql.md"),
    # Troubleshooting (30) — 41-70
    (41, "How do you triage sustained replication lag on one secondary while others stay current?", "Hard", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (42, "What steps isolate application slowness from database slowness in a replica set?", "Medium", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (43, "How would you debug a query that regressed after a deployment with no index change?", "Hard", "Senior Engineer", "Troubleshooting", "03-query-performance/explain-plan.md"),
    (44, "What causes jumbo chunks and how do they block the balancer?", "Hard", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (45, "How do you remediate a hot shard created by a monotonic timestamp shard key?", "Hard", "Architect", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (46, "What symptoms indicate the oplog is too small for maintenance catch-up?", "Medium", "Lead", "Troubleshooting", "02-core-mongodb/replication.md"),
    (47, "How would you handle a secondary that fell off the oplog and needs resync?", "Hard", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (48, "What is rollback after failover and how do clients detect rolled-back writes?", "Hard", "Architect", "Troubleshooting", "02-core-mongodb/replication.md"),
    (49, "How do you kill a runaway aggregation without impacting unrelated workloads?", "Medium", "Senior Engineer", "Troubleshooting", "04-production-operations/monitoring.md"),
    (50, "What `currentOp` fields identify a long-running transaction blocking others?", "Hard", "Lead", "Troubleshooting", "02-core-mongodb/transactions.md"),
    (51, "How would you troubleshoot elections flapping during network instability?", "Hard", "Architect", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (52, "What disk I/O patterns suggest checkpoint storms on WiredTiger?", "Hard", "Lead", "Troubleshooting", "02-core-mongodb/storage-engine.md"),
    (53, "How do page faults manifest in latency and which metrics confirm cache pressure?", "Medium", "Senior Engineer", "Troubleshooting", "04-production-operations/capacity-planning.md"),
    (54, "What explains COLLSCAN on a collection you believed was indexed?", "Medium", "Senior Engineer", "Troubleshooting", "03-query-performance/explain-plan.md"),
    (55, "How do you troubleshoot `$lookup` performing COLLSCAN on the foreign collection?", "Hard", "Senior Engineer", "Troubleshooting", "03-query-performance/query-optimization.md"),
    (56, "What shard metadata issues cause mongos to return stale routing?", "Hard", "Architect", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (57, "How would you diagnose connection storms from misconfigured connection pools?", "Medium", "Lead", "Troubleshooting", "04-production-operations/performance.md"),
    (58, "What TTL index misconfigurations cause documents to never expire?", "Easy", "Senior Engineer", "Troubleshooting", "03-query-performance/ttl-index.md"),
    (59, "How do you troubleshoot Atlas `mongodb+srv` DNS resolution failures in corporate networks?", "Medium", "Lead", "Troubleshooting", "01-fundamentals/atlas-basics.md"),
    (60, "What runbook steps recover from accidental `dropDatabase` in production?", "Hard", "Architect", "Troubleshooting", "04-production-operations/backup-recovery.md"),
    (61, "How do you detect and fix index builds stuck in background on large collections?", "Hard", "Lead", "Troubleshooting", "03-query-performance/indexes.md"),
    (62, "What causes `$text` queries to return unexpected stems or misses on SKUs?", "Medium", "Senior Engineer", "Troubleshooting", "03-query-performance/text-search.md"),
    (63, "How would you debug geospatial queries returning empty results for valid coordinates?", "Medium", "Senior Engineer", "Troubleshooting", "03-query-performance/geospatial.md"),
    (64, "What transaction errors appear when collections don't exist before commit?", "Medium", "Senior Engineer", "Troubleshooting", "02-core-mongodb/transactions.md"),
    (65, "How do you troubleshoot write concern timeouts under cross-region replication?", "Hard", "Lead", "Troubleshooting", "02-core-mongodb/replication.md"),
    (66, "What signs indicate the balancer is disabled or stuck?", "Medium", "Lead", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (67, "How would you investigate memory climbing until mongod is OOM-killed?", "Hard", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    (68, "What profiler settings are safe for intermittent slow-query capture in production?", "Medium", "Senior Engineer", "Troubleshooting", "04-production-operations/monitoring.md"),
    (69, "How do you validate a restored backup before cutting traffic over?", "Hard", "Architect", "Troubleshooting", "04-production-operations/backup-recovery.md"),
    (70, "What is your first-hour incident checklist for a primary that won't rejoin the replica set?", "Hard", "Lead", "Troubleshooting", "04-production-operations/troubleshooting.md"),
    # Performance (25) — 71-95
    (71, "How do you use explain output to decide between a new compound index and a covered query rewrite?", "Hard", "Senior Engineer", "Performance", "03-query-performance/explain-plan.md"),
    (72, "What ESR ordering would you use for `{ status, createdAt, amount }` filters?", "Medium", "Senior Engineer", "Performance", "03-query-performance/indexes.md"),
    (73, "When does index intersection help and when should you avoid relying on it?", "Medium", "Lead", "Performance", "03-query-performance/query-optimization.md"),
    (74, "How do partial indexes reduce write amplification for status-filtered queries?", "Medium", "Senior Engineer", "Performance", "03-query-performance/indexes.md"),
    (75, "What projection changes turn an IXSCAN+FETCH into a covered query?", "Medium", "Senior Engineer", "Performance", "03-query-performance/query-optimization.md"),
    (76, "How does large `skip` pagination degrade performance and what pattern replaces it?", "Easy", "Senior Engineer", "Performance", "04-production-operations/performance.md"),
    (77, "How do you tune aggregation `$lookup` pipeline order for index use?", "Hard", "Lead", "Performance", "03-query-performance/aggregation-pipeline.md"),
    (78, "When is `allowDiskUse: true` acceptable versus a design smell?", "Medium", "Lead", "Performance", "03-query-performance/aggregation-pipeline.md"),
    (79, "How does WiredTiger cache sizing affect p99 read latency?", "Hard", "Architect", "Performance", "02-core-mongodb/storage-engine.md"),
    (80, "What compression settings trade CPU for disk I/O on write-heavy workloads?", "Medium", "Lead", "Performance", "02-core-mongodb/storage-engine.md"),
    (81, "How do you right-size `maxPoolSize` across 50 application pods?", "Hard", "Lead", "Performance", "04-production-operations/performance.md"),
    (82, "What bulk write patterns maximize insert throughput on sharded collections?", "Medium", "Senior Engineer", "Performance", "04-production-operations/performance.md"),
    (83, "How do hashed shard keys affect range query performance?", "Medium", "Senior Engineer", "Performance", "02-core-mongodb/sharding.md"),
    (84, "What index hygiene process prevents unbounded index growth over years?", "Medium", "Lead", "Performance", "04-production-operations/monitoring.md"),
    (85, "How would you load-test shard key distribution before production cutover?", "Hard", "Architect", "Performance", "02-core-mongodb/sharding.md"),
    (86, "What regex patterns can use indexes and which force COLLSCAN?", "Medium", "Senior Engineer", "Performance", "03-query-performance/query-optimization.md"),
    (87, "How does read preference nearest reduce latency at consistency cost?", "Medium", "Senior Engineer", "Performance", "02-core-mongodb/replication.md"),
    (88, "What Atlas Performance Advisor suggestions do you auto-apply versus review?", "Medium", "Lead", "Performance", "04-production-operations/monitoring.md"),
    (89, "How do write-heavy indexes on high-cardinality fields impact checkpoint I/O?", "Hard", "Lead", "Performance", "02-core-mongodb/storage-engine.md"),
    (90, "When does embedding outperform `$lookup` for read latency at scale?", "Medium", "Senior Engineer", "Performance", "02-core-mongodb/schema-design.md"),
    (91, "How do you benchmark working set size before hardware procurement?", "Hard", "Architect", "Performance", "04-production-operations/capacity-planning.md"),
    (92, "What `$facet` patterns reduce round trips without exploding memory?", "Medium", "Senior Engineer", "Performance", "03-query-performance/aggregation-pipeline.md"),
    (93, "How does collation-aware indexing affect sort stage elimination?", "Hard", "Senior Engineer", "Performance", "03-query-performance/indexes.md"),
    (94, "What pre-split strategy avoids hot chunks during initial bulk load?", "Hard", "Lead", "Performance", "02-core-mongodb/sharding.md"),
    (95, "How do you tune oplog size for write bursts without wasting disk?", "Medium", "Lead", "Performance", "02-core-mongodb/replication.md"),
    # Reliability (20) — 96-115
    (96, "How does `w: \"majority\"` prevent data loss during primary failover?", "Hard", "Architect", "Reliability", "02-core-mongodb/replication.md"),
    (97, "When is `readConcern: \"majority\"` required for read-your-writes across failover?", "Hard", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (98, "What is linearizable read concern and when is it worth the latency cost?", "Hard", "Architect", "Reliability", "02-core-mongodb/replication.md"),
    (99, "How do retryable writes interact with idempotent application logic?", "Medium", "Senior Engineer", "Reliability", "02-core-mongodb/transactions.md"),
    (100, "What failure modes do arbiters introduce in a three-node replica set?", "Medium", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (101, "How do hidden and delayed secondaries support backup and forensic reads?", "Medium", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (102, "What two-phase commit steps occur on multi-shard transaction commit?", "Hard", "Architect", "Reliability", "02-core-mongodb/transactions.md"),
    (103, "How long can transactions run before `transactionLifetimeLimitSeconds` aborts them?", "Medium", "Senior Engineer", "Reliability", "02-core-mongodb/transactions.md"),
    (104, "What write concern settings would you mandate for payment ledger updates?", "Hard", "Architect", "Reliability", "02-core-mongodb/replication.md"),
    (105, "How does journal durability (`j: true`) complement replication?", "Medium", "Lead", "Reliability", "02-core-mongodb/storage-engine.md"),
    (106, "What RPO/RTO targets are realistic with Atlas continuous backup?", "Hard", "Architect", "Reliability", "04-production-operations/backup-recovery.md"),
    (107, "How do you test failover without corrupting idempotent downstream consumers?", "Hard", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (108, "What happens to in-flight writes during a stepped-down primary?", "Medium", "Senior Engineer", "Reliability", "02-core-mongodb/replication.md"),
    (109, "How does replica set member priority influence planned maintenance windows?", "Medium", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (110, "When are multi-document transactions an anti-pattern for high-throughput domains?", "Hard", "Architect", "Reliability", "02-core-mongodb/transactions.md"),
    (111, "How do change streams guarantee resume tokens across brief disconnects?", "Medium", "Senior Engineer", "Reliability", "02-core-mongodb/replication.md"),
    (112, "What backup strategy covers config servers in a sharded cluster DR plan?", "Hard", "Architect", "Reliability", "04-production-operations/backup-recovery.md"),
    (113, "How would you validate majority write concern across three availability zones?", "Hard", "Architect", "Reliability", "02-core-mongodb/replication.md"),
    (114, "What application patterns avoid dual-write inconsistencies without distributed transactions?", "Hard", "Architect", "Reliability", "02-core-mongodb/schema-design.md"),
    (115, "How does oplog retention window relate to delayed member lag configuration?", "Medium", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    # Security (15) — 116-130
    (116, "How do you enforce least-privilege RBAC for application versus ops users?", "Medium", "Lead", "Security", "01-fundamentals/atlas-basics.md"),
    (117, "What network controls does Atlas offer beyond IP allowlists?", "Medium", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    (118, "When is VPC peering or PrivateLink mandatory for regulated workloads?", "Hard", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    (119, "How do you rotate database credentials without application downtime?", "Hard", "Lead", "Security", "01-fundamentals/atlas-basics.md"),
    (120, "What TLS configuration is required for production client connections?", "Medium", "Senior Engineer", "Security", "01-fundamentals/atlas-basics.md"),
    (121, "How does encryption at rest differ between Atlas and self-managed deployments?", "Medium", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    (122, "What audit logging would you enable for SOX or HIPAA MongoDB environments?", "Hard", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    (123, "How do you prevent `$where` and server-side JavaScript from becoming security holes?", "Medium", "Lead", "Security", "01-fundamentals/crud.md"),
    (124, "What risks does exposing mongod directly to the internet create?", "Easy", "Senior Engineer", "Security", "02-core-mongodb/architecture.md"),
    (125, "How would you segment tenant data in a shared cluster using roles and namespaces?", "Hard", "Architect", "Security", "02-core-mongodb/sharding.md"),
    (126, "What field-level encryption tradeoffs apply to PII in documents?", "Hard", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    (127, "How do Atlas database users differ from cloud provider IAM for automation?", "Medium", "Lead", "Security", "01-fundamentals/atlas-basics.md"),
    (128, "What secrets management pattern avoids credentials in application.yml?", "Easy", "Senior Engineer", "Security", "01-fundamentals/atlas-basics.md"),
    (129, "How do you secure mongosh admin access in production break-glass scenarios?", "Medium", "Lead", "Security", "04-production-operations/monitoring.md"),
    (130, "What compliance implications exist when Atlas regions cross sovereignty boundaries?", "Hard", "Architect", "Security", "01-fundamentals/atlas-basics.md"),
    # Additional balanced (20) — 131-150
    (131, "How does WiredTiger MVCC allow concurrent readers during writer activity?", "Hard", "Senior Engineer", "Architecture", "02-core-mongodb/storage-engine.md"),
    (132, "What checkpoint frequency tradeoffs affect crash recovery time?", "Medium", "Lead", "Architecture", "02-core-mongodb/storage-engine.md"),
    (133, "How do elections choose a new primary when priority values differ?", "Medium", "Senior Engineer", "Reliability", "02-core-mongodb/replication.md"),
    (134, "What oplog entry types appear for idempotent replays on secondaries?", "Hard", "Senior Engineer", "Architecture", "02-core-mongodb/replication.md"),
    (135, "How does the aggregation optimizer push `$match` before `$lookup`?", "Hard", "Senior Engineer", "Performance", "03-query-performance/aggregation-pipeline.md"),
    (136, "What `executionStats` ratio triggers an index creation ticket in your team?", "Medium", "Lead", "Performance", "03-query-performance/explain-plan.md"),
    (137, "How do mongostat opcounters help distinguish read versus write saturation?", "Medium", "Senior Engineer", "Performance", "04-production-operations/monitoring.md"),
    (138, "What chunk size defaults affect migration frequency on sharded clusters?", "Medium", "Senior Engineer", "Architecture", "02-core-mongodb/sharding.md"),
    (139, "How would you reshard a collection when business requirements invalidate the shard key?", "Hard", "Architect", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (140, "What Atlas backup window settings minimize impact on production I/O?", "Medium", "Lead", "Reliability", "04-production-operations/backup-recovery.md"),
    (141, "How do multikey indexes behave when array fields grow unbounded?", "Medium", "Senior Engineer", "Performance", "03-query-performance/indexes.md"),
    (142, "When does Atlas Search justify operational complexity over `$text` indexes?", "Medium", "Architect", "Architecture", "03-query-performance/text-search.md"),
    (143, "How do write timestamps as shard keys create hotspot chunks?", "Easy", "Senior Engineer", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (144, "What `$expr` queries complicate index use and how do you refactor them?", "Hard", "Senior Engineer", "Performance", "03-query-performance/query-optimization.md"),
    (145, "How does `nearest` read preference interact with replica set tag sets?", "Hard", "Lead", "Reliability", "02-core-mongodb/replication.md"),
    (146, "What storage growth model includes indexes and oplog for sharded deployments?", "Hard", "Architect", "Performance", "04-production-operations/capacity-planning.md"),
    (147, "How do you design session TTL indexes that survive clock skew?", "Medium", "Senior Engineer", "Reliability", "03-query-performance/ttl-index.md"),
    (148, "What hybrid search architecture combines Atlas Search with operational MongoDB data?", "Hard", "Architect", "Architecture", "03-query-performance/text-search.md"),
    (149, "How would you explain chunk migration impact to application owners before rebalancing?", "Medium", "Lead", "Troubleshooting", "02-core-mongodb/sharding.md"),
    (150, "What handbook topics would you assign a new hire versus a staff engineer in onboarding?", "Easy", "Lead", "Architecture", "07-learning-paths/mongodb-senior-engineer-path.md"),
]
