"""Top 150 Redis interview questions — shared data for handbook generation."""

QUESTIONS = [
    # Architecture (40) — 1-40
    (1, "Why does Redis use a single-threaded command execution model, and when do I/O threads change that picture?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/architecture.md"),
    (2, "How would you choose between standalone Redis, Sentinel, and Cluster for a new payment-adjacent cache?", "Hard", "Architect", "Architecture", "01-fundamentals/architecture.md"),
    (3, "What architectural role does Redis play when it is cache versus when it is the primary data store?", "Medium", "Architect", "Architecture", "01-fundamentals/architecture.md"),
    (4, "How does the global keyspace dictionary influence hot-key and big-key failure modes at scale?", "Hard", "Senior Engineer", "Architecture", "01-fundamentals/architecture.md"),
    (5, "When would you shard with Redis Cluster instead of vertical scaling a single primary?", "Hard", "Architect", "Architecture", "03-redis-internals/cluster.md"),
    (6, "How do hash tags change your key design when you need multi-key atomicity in Cluster?", "Hard", "Lead", "Architecture", "03-redis-internals/cluster.md"),
    (7, "What is the mental model for 16384 hash slots, and why not more or fewer?", "Medium", "Senior Engineer", "Architecture", "03-redis-internals/cluster.md"),
    (8, "How do MOVED and ASK redirects differ in client architecture during normal ops versus resharding?", "Hard", "Lead", "Architecture", "03-redis-internals/redis-protocol.md"),
    (9, "When is Sentinel the right HA layer versus managed cloud failover you do not operate?", "Medium", "Architect", "Architecture", "03-redis-internals/sentinel.md"),
    (10, "How would you diagram request flow from application through connection pool to Redis command thread?", "Medium", "Senior Engineer", "Architecture", "03-redis-internals/redis-protocol.md"),
    (11, "What data type would you pick for a user profile with frequent single-field updates, and why not a JSON string?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/data-structures.md"),
    (12, "When are Redis Streams architecturally appropriate versus an external log like Kafka?", "Hard", "Architect", "Architecture", "07-comparisons/redis-vs-kafka.md"),
    (13, "When are Redis lists or Streams appropriate versus RabbitMQ for task distribution?", "Hard", "Architect", "Architecture", "07-comparisons/redis-vs-rabbitmq.md"),
    (14, "How does Pub/Sub fit into cache invalidation architecture without becoming a system of record?", "Medium", "Lead", "Architecture", "04-distributed-systems/pub-sub.md"),
    (15, "What tradeoffs does Redis offer versus Memcached for a pure session cache layer?", "Medium", "Architect", "Architecture", "07-comparisons/redis-vs-memcached.md"),
    (16, "How would you isolate tenant traffic on a shared Redis cluster without cross-tenant key collisions?", "Hard", "Architect", "Architecture", "03-redis-internals/cluster.md"),
    (17, "When do Redis modules (RedisJSON, RediSearch) change your storage architecture versus plain hashes?", "Medium", "Lead", "Architecture", "01-fundamentals/data-structures.md"),
    (18, "How does TTL-at-key-level architecture affect session design versus field-level expiry needs?", "Medium", "Senior Engineer", "Architecture", "01-fundamentals/data-structures.md"),
    (19, "What signals indicate a workload has outgrown a single primary before ops teams admit it?", "Hard", "Architect", "Architecture", "06-performance-operations/capacity-planning.md"),
    (20, "How would you place Redis relative to the database in a read-heavy catalog service?", "Medium", "Senior Engineer", "Architecture", "05-production-patterns/caching-patterns.md"),
    (21, "When is replica read scaling architecturally safe, and when does it violate freshness requirements?", "Hard", "Lead", "Architecture", "03-redis-internals/replication.md"),
    (22, "How do persistence settings change the architecture story when Redis is marketed as a cache only?", "Medium", "Architect", "Architecture", "03-redis-internals/persistence.md"),
    (23, "What is the architectural impact of running Redis in Kubernetes with ephemeral versus persistent volumes?", "Hard", "Architect", "Architecture", "03-redis-internals/persistence.md"),
    (24, "How would you design key namespaces for microservices sharing one cluster without coupling?", "Medium", "Lead", "Architecture", "01-fundamentals/data-structures.md"),
    (25, "When does colocating rate limiting, sessions, and entity cache in one cluster create blast-radius risk?", "Hard", "Architect", "Architecture", "05-production-patterns/rate-limiter.md"),
    (26, "How does active-active multi-region Redis differ architecturally from single-region Cluster plus replication?", "Hard", "Architect", "Architecture", "03-redis-internals/cluster.md"),
    (27, "What client topology changes when applications must be Sentinel-aware versus Cluster-aware?", "Medium", "Senior Engineer", "Architecture", "03-redis-internals/sentinel.md"),
    (28, "How would you justify Redis as a delay queue using sorted sets versus a dedicated scheduler?", "Medium", "Lead", "Architecture", "02-core-redis/sorted-sets.md"),
    (29, "When is HyperLogLog the correct architectural choice for analytics versus sets or bitmaps?", "Medium", "Senior Engineer", "Architecture", "02-core-redis/hyperloglog.md"),
    (30, "How do Lua scripts affect your architecture for atomic inventory decrements?", "Hard", "Lead", "Architecture", "04-distributed-systems/lua-scripts.md"),
    (31, "What architecture pitfalls appear when using Redis transactions across many hot keys?", "Hard", "Senior Engineer", "Architecture", "04-distributed-systems/transactions.md"),
    (32, "How would you blueprint replica count and sentinel quorum in an ADR for 99.95% cache availability?", "Hard", "Architect", "Architecture", "03-redis-internals/sentinel.md"),
    (33, "When does TLS termination at proxy versus Redis native TLS change trust boundaries?", "Medium", "Architect", "Architecture", "03-redis-internals/redis-protocol.md"),
    (34, "How does connection pooling architecture prevent thundering herd on Redis reconnect after failover?", "Hard", "Lead", "Architecture", "03-redis-internals/sentinel.md"),
    (35, "What architectural constraints does Redis impose on exactly-once processing semantics?", "Hard", "Architect", "Architecture", "04-distributed-systems/streams.md"),
    (36, "How would you map cache patterns (aside, through, behind) to team ownership boundaries?", "Medium", "Architect", "Architecture", "05-production-patterns/caching-patterns.md"),
    (37, "When is noeviction the correct maxmemory-policy for a non-cache primary store?", "Medium", "Lead", "Architecture", "06-performance-operations/eviction-policies.md"),
    (38, "How do Redis ACLs change multi-tenant architecture compared to shared-password eras?", "Medium", "Architect", "Architecture", "01-fundamentals/architecture.md"),
    (39, "What cross-datacenter replication options would you compare before choosing Redis Cluster only?", "Hard", "Architect", "Architecture", "03-redis-internals/replication.md"),
    (40, "How would you defend Redis versus a cloud vendor cache in an enterprise architecture review?", "Hard", "Architect", "Architecture", "07-comparisons/redis-vs-memcached.md"),
    # Troubleshooting (30) — 41-70
    (41, "How do you triage sudden memory growth when used_memory rises but key count looks stable?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (42, "What steps isolate whether latency spikes are network, slow commands, or fork-related COW pressure?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (43, "How would you diagnose replication lag that only appears during peak write hours?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (44, "What does LATENCY DOCTOR tell you that SLOWLOG alone cannot?", "Medium", "Senior Engineer", "Troubleshooting", "06-performance-operations/monitoring.md"),
    (45, "How do you find and remediate hot keys without KEYS or MONITOR in production?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (46, "What symptoms distinguish a big-key problem from a hot-key problem on a single-threaded primary?", "Hard", "Senior Engineer", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (47, "How would you troubleshoot Cluster slot imbalance after adding a new primary?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (48, "What is your runbook when clients report MOVED storms after a resharding operation?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (49, "How do you debug Sentinel failover loops where primaries flap every few minutes?", "Hard", "Architect", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (50, "What causes writes to fail with OOM errors despite setting maxmemory?", "Medium", "Senior Engineer", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (51, "How would you investigate volatile-lru not evicting keys when memory is full?", "Medium", "Senior Engineer", "Troubleshooting", "06-performance-operations/eviction-policies.md"),
    (52, "What forensic steps follow a partial AOF rewrite failure on restart?", "Hard", "Lead", "Troubleshooting", "03-redis-internals/persistence.md"),
    (53, "How do you detect and fix replica serving stale reads that break business rules?", "Hard", "Lead", "Troubleshooting", "03-redis-internals/replication.md"),
    (54, "What explains consumer group pending entries growing without XPENDING visibility in dashboards?", "Hard", "Senior Engineer", "Troubleshooting", "04-distributed-systems/streams.md"),
    (55, "How would you troubleshoot cache stampede after a popular key expires simultaneously?", "Hard", "Lead", "Troubleshooting", "05-production-patterns/cache-avalanche.md"),
    (56, "What mitigations apply when cache penetration hammers the database for non-existent IDs?", "Hard", "Lead", "Troubleshooting", "05-production-patterns/cache-penetration.md"),
    (57, "How do you debug distributed lock double-execution after TTL expiry?", "Hard", "Architect", "Troubleshooting", "04-distributed-systems/distributed-lock.md"),
    (58, "What would you check when BGSAVE consistently fails during memory pressure events?", "Hard", "Lead", "Troubleshooting", "03-redis-internals/persistence.md"),
    (59, "How do you triage high CPU on Redis when QPS has not increased?", "Medium", "Senior Engineer", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (60, "What client-side symptoms indicate connection pool exhaustion versus server maxclients?", "Medium", "Senior Engineer", "Troubleshooting", "06-performance-operations/monitoring.md"),
    (61, "How would you debug a Lua script that intermittently fails with CROSSSLOT errors in Cluster?", "Hard", "Lead", "Troubleshooting", "04-distributed-systems/lua-scripts.md"),
    (62, "What runbook steps apply when one shard in Cluster hits 100% CPU while others are idle?", "Hard", "Lead", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (63, "How do you identify commands blocking the event loop beyond SLOWLOG threshold tuning?", "Hard", "Senior Engineer", "Troubleshooting", "06-performance-operations/performance-tuning.md"),
    (64, "What causes mem_fragmentation_ratio to climb and when is active defrag appropriate?", "Hard", "Lead", "Troubleshooting", "03-redis-internals/memory-management.md"),
    (65, "How would you troubleshoot session loss after a Sentinel failover during peak traffic?", "Hard", "Lead", "Troubleshooting", "05-production-patterns/session-store.md"),
    (66, "What diagnostics differentiate network partition from overloaded primary during timeout storms?", "Hard", "Architect", "Troubleshooting", "06-performance-operations/troubleshooting.md"),
    (67, "How do you debug rate limiter drift when counters look correct per key but limits feel wrong?", "Medium", "Senior Engineer", "Troubleshooting", "05-production-patterns/rate-limiter.md"),
    (68, "What steps validate AOF integrity before promoting a rebuilt replica?", "Hard", "Lead", "Troubleshooting", "03-redis-internals/persistence.md"),
    (69, "How would you investigate Pub/Sub subscribers missing invalidation messages intermittently?", "Medium", "Lead", "Troubleshooting", "04-distributed-systems/pub-sub.md"),
    (70, "What is your incident checklist when Redis latency breaches SLO but INFO shows low ops/sec?", "Hard", "Architect", "Troubleshooting", "06-performance-operations/monitoring.md"),
    # Performance (25) — 71-95
    (71, "How does pipelining improve throughput without changing Redis single-threaded execution?", "Medium", "Senior Engineer", "Performance", "06-performance-operations/performance-tuning.md"),
    (72, "What pipeline batch size tradeoffs would you test against a 5ms p99 latency SLO?", "Hard", "Lead", "Performance", "06-performance-operations/performance-tuning.md"),
    (73, "When does MGET outperform pipelined GET for the same key batch?", "Medium", "Senior Engineer", "Performance", "06-performance-operations/performance-tuning.md"),
    (74, "How do large values in strings affect network and latency more than CPU on the server?", "Medium", "Senior Engineer", "Performance", "02-core-redis/strings.md"),
    (75, "What command choices turn O(1) expectations into O(N) event-loop blockers?", "Hard", "Lead", "Performance", "06-performance-operations/performance-tuning.md"),
    (76, "How would you tune io-threads and io-threads-do-reads for a read-heavy workload?", "Hard", "Lead", "Performance", "01-fundamentals/architecture.md"),
    (77, "What is the performance impact of appendfsync always versus everysec for write-heavy caches?", "Hard", "Architect", "Performance", "03-redis-internals/persistence.md"),
    (78, "How does RDB fork latency interact with memory overcommit and COW during BGSAVE?", "Hard", "Lead", "Performance", "03-redis-internals/persistence.md"),
    (79, "When does allkeys-lfu outperform allkeys-lru for skewed access patterns?", "Medium", "Senior Engineer", "Performance", "06-performance-operations/eviction-policies.md"),
    (80, "How do maxmemory-samples settings affect eviction accuracy and CPU?", "Medium", "Senior Engineer", "Performance", "06-performance-operations/eviction-policies.md"),
    (81, "What encoding upgrades cause latency cliffs as small hashes grow past listpack thresholds?", "Hard", "Lead", "Performance", "03-redis-internals/memory-management.md"),
    (82, "How would you benchmark UNLINK versus DEL for bulk key deletion in production maintenance?", "Medium", "Senior Engineer", "Performance", "06-performance-operations/performance-tuning.md"),
    (83, "What client connection pool sizing formula avoids Redis maxclients saturation?", "Hard", "Lead", "Performance", "06-performance-operations/capacity-planning.md"),
    (84, "How does TLS add latency, and where would you terminate TLS for cache workloads?", "Medium", "Architect", "Performance", "03-redis-internals/redis-protocol.md"),
    (85, "When does sharding with Cluster improve throughput versus larger single-instance hardware?", "Hard", "Architect", "Performance", "03-redis-internals/cluster.md"),
    (86, "How do BITOP and BITCOUNT scale poorly on large sparse bitmaps?", "Medium", "Senior Engineer", "Performance", "02-core-redis/bitmaps.md"),
    (87, "What ZSET range query patterns need LIMIT to protect p99 latency?", "Medium", "Senior Engineer", "Performance", "02-core-redis/sorted-sets.md"),
    (88, "How would you optimize a sliding-window rate limiter implemented with sorted sets?", "Hard", "Lead", "Performance", "05-production-patterns/rate-limiter.md"),
    (89, "What latency gains come from switching HGETALL to HMGET or HSCAN on wide hashes?", "Medium", "Senior Engineer", "Performance", "02-core-redis/hashes.md"),
    (90, "How does replication backlog sizing affect partial resync performance after brief outages?", "Medium", "Lead", "Performance", "03-redis-internals/replication.md"),
    (91, "What OS-level tuning (transparent huge pages, somaxconn) still matters for Redis in 2026?", "Hard", "Lead", "Performance", "06-performance-operations/performance-tuning.md"),
    (92, "How would you load-test Redis Cluster to find the first bottleneck: CPU, network, or slot skew?", "Hard", "Architect", "Performance", "06-performance-operations/capacity-planning.md"),
    (93, "When does probabilistic early expiration improve tail latency versus naive TTL refresh?", "Hard", "Lead", "Performance", "05-production-patterns/cache-avalanche.md"),
    (94, "How do Streams MAXLEN approximate trimming trade memory for ingestion throughput?", "Medium", "Senior Engineer", "Performance", "04-distributed-systems/streams.md"),
    (95, "What metrics prove your cache hit ratio improvements actually reduced database load?", "Medium", "Lead", "Performance", "06-performance-operations/monitoring.md"),
    # Reliability (20) — 96-115
    (96, "What data loss window exists with appendfsync everysec if the process crashes mid-second?", "Medium", "Senior Engineer", "Reliability", "03-redis-internals/persistence.md"),
    (97, "How do RDB snapshots complement AOF for faster restarts in hybrid persistence?", "Medium", "Lead", "Reliability", "03-redis-internals/persistence.md"),
    (98, "When would you disable persistence entirely, and what failure modes remain acceptable?", "Medium", "Architect", "Reliability", "03-redis-internals/persistence.md"),
    (99, "How does min-replicas-to-write protect against write loss during partition events?", "Hard", "Architect", "Reliability", "03-redis-internals/replication.md"),
    (100, "What is the role of WAIT after a write when clients require stronger durability than async replication?", "Hard", "Lead", "Reliability", "03-redis-internals/replication.md"),
    (101, "How would you design failover testing for Sentinel without corrupting production data?", "Hard", "Architect", "Reliability", "03-redis-internals/sentinel.md"),
    (102, "What split-brain scenarios can occur with misconfigured Sentinel quorum?", "Hard", "Architect", "Reliability", "03-redis-internals/sentinel.md"),
    (103, "How do replica-read-only and ACLs combine to prevent accidental writes to secondaries?", "Medium", "Senior Engineer", "Reliability", "03-redis-internals/replication.md"),
    (104, "What happens to in-flight Pub/Sub messages during primary failover?", "Medium", "Lead", "Reliability", "04-distributed-systems/pub-sub.md"),
    (105, "How do consumer groups provide at-least-once delivery, and what idempotency must apps implement?", "Hard", "Senior Engineer", "Reliability", "04-distributed-systems/streams.md"),
    (106, "Why does MULTI/EXEC not provide rollback semantics like a relational transaction?", "Medium", "Senior Engineer", "Reliability", "04-distributed-systems/transactions.md"),
    (107, "How do fencing tokens prevent stale lock holders from corrupting durable storage?", "Hard", "Architect", "Reliability", "04-distributed-systems/distributed-lock.md"),
    (108, "What correctness gaps remain with SET key token NX PX even when unlock uses Lua?", "Hard", "Architect", "Reliability", "04-distributed-systems/distributed-lock.md"),
    (109, "How would you argue for or against Redlock in a multi-datacenter inventory system?", "Hard", "Architect", "Reliability", "04-distributed-systems/distributed-lock.md"),
    (110, "What disaster recovery RPO do you get from hourly RDB plus AOF everysec combined?", "Hard", "Architect", "Reliability", "03-redis-internals/persistence.md"),
    (111, "How does Cluster handle primary failure when replicas exist versus when they do not?", "Hard", "Lead", "Reliability", "03-redis-internals/cluster.md"),
    (112, "What reliability risks appear when resharding moves slots during peak traffic?", "Hard", "Lead", "Reliability", "03-redis-internals/cluster.md"),
    (113, "How do you keep cache and database consistent under write-through versus write-behind?", "Hard", "Lead", "Reliability", "05-production-patterns/cache-invalidation.md"),
    (114, "What session durability expectations are realistic when Redis is only a cache?", "Medium", "Senior Engineer", "Reliability", "05-production-patterns/session-store.md"),
    (115, "How would you validate backup restores for AOF rewrite corruption edge cases?", "Hard", "Lead", "Reliability", "03-redis-internals/persistence.md"),
    # Scalability (15) — 116-130
    (116, "How do you estimate Redis memory for N keys given average value size and encoding overhead?", "Hard", "Lead", "Scalability", "06-performance-operations/capacity-planning.md"),
    (117, "When does adding replicas stop helping read scale because the primary is still the bottleneck?", "Hard", "Architect", "Scalability", "03-redis-internals/replication.md"),
    (118, "How many primaries and replicas would you plan for a 500 GB working set with 200k ops/sec?", "Hard", "Architect", "Scalability", "06-performance-operations/capacity-planning.md"),
    (119, "What key design choices cause one Cluster shard to absorb disproportionate traffic?", "Hard", "Lead", "Scalability", "05-production-patterns/cache-breakdown.md"),
    (120, "How would you split a hot key across logical shards at the application layer?", "Hard", "Lead", "Scalability", "05-production-patterns/cache-breakdown.md"),
    (121, "When does horizontal Cluster scaling hit coordination overhead diminishing returns?", "Hard", "Architect", "Scalability", "03-redis-internals/cluster.md"),
    (122, "How do global rate limit counters scale when a single INCR key becomes hot?", "Hard", "Lead", "Scalability", "05-production-patterns/rate-limiter.md"),
    (123, "What growth triggers move you from one large instance to Cluster beyond memory alone?", "Hard", "Architect", "Scalability", "06-performance-operations/capacity-planning.md"),
    (124, "How does replication factor affect memory and network costs at 10x data growth?", "Medium", "Lead", "Scalability", "03-redis-internals/replication.md"),
    (125, "When do Streams with many consumer groups create memory pressure versus Kafka retention?", "Hard", "Architect", "Scalability", "07-comparisons/redis-vs-kafka.md"),
    (126, "How would you plan slot migration windows to scale out Cluster without client outages?", "Hard", "Lead", "Scalability", "03-redis-internals/cluster.md"),
    (127, "What is the scalability ceiling of single-threaded command processing per core?", "Medium", "Senior Engineer", "Scalability", "01-fundamentals/architecture.md"),
    (128, "How do connection counts from thousands of pods affect Redis scalability in Kubernetes?", "Hard", "Lead", "Scalability", "06-performance-operations/capacity-planning.md"),
    (129, "When does caching null results with short TTL scale better than Bloom filters?", "Medium", "Senior Engineer", "Scalability", "05-production-patterns/cache-penetration.md"),
    (130, "How would you model year-over-year key growth for finance-approved capacity budgets?", "Hard", "Architect", "Scalability", "06-performance-operations/capacity-planning.md"),
    # Patterns & Coordination (20) — 131-150
    (131, "Walk through cache-aside read and write invalidation for an updated product record.", "Medium", "Senior Engineer", "Patterns", "05-production-patterns/caching-patterns.md"),
    (132, "How does write-behind improve write latency while risking data loss on crash?", "Hard", "Lead", "Patterns", "05-production-patterns/cache-invalidation.md"),
    (133, "What singleflight or lock pattern prevents rebuild stampede on a popular cache miss?", "Hard", "Lead", "Patterns", "05-production-patterns/cache-breakdown.md"),
    (134, "How would you implement TTL jitter to mitigate synchronized expiry avalanches?", "Medium", "Senior Engineer", "Patterns", "05-production-patterns/cache-avalanche.md"),
    (135, "When is a Bloom filter worth adding versus caching empty placeholders?", "Hard", "Lead", "Patterns", "05-production-patterns/cache-penetration.md"),
    (136, "How do you implement a correct distributed lock release with token verification?", "Hard", "Senior Engineer", "Patterns", "04-distributed-systems/distributed-lock.md"),
    (137, "Why prefer Lua over WATCH/MULTI for contested hot keys?", "Hard", "Lead", "Patterns", "04-distributed-systems/lua-scripts.md"),
    (138, "How does XREADGROUP BLOCK behave differently from BLPOP for worker pools?", "Medium", "Senior Engineer", "Patterns", "04-distributed-systems/streams.md"),
    (139, "What is the recovery procedure for poison messages stuck in XPENDING?", "Hard", "Lead", "Patterns", "04-distributed-systems/streams.md"),
    (140, "How would you choose fixed-window versus sliding-window rate limits for an API gateway?", "Medium", "Senior Engineer", "Patterns", "05-production-patterns/rate-limiter.md"),
    (141, "What session fields belong in Redis versus only in signed cookies?", "Medium", "Senior Engineer", "Patterns", "05-production-patterns/session-store.md"),
    (142, "How does Pub/Sub-based cache invalidation avoid stale local caches in multi-tier apps?", "Medium", "Lead", "Patterns", "05-production-patterns/cache-invalidation.md"),
    (143, "When should lists be retired in favor of Streams for work queues?", "Medium", "Senior Engineer", "Patterns", "02-core-redis/lists.md"),
    (144, "How do hash tags enable atomic multi-key updates in Cluster for order line items?", "Hard", "Lead", "Patterns", "03-redis-internals/cluster.md"),
    (145, "What pipeline patterns reduce round trips in bulk session refresh jobs?", "Medium", "Senior Engineer", "Patterns", "06-performance-operations/performance-tuning.md"),
    (146, "How would you implement a token bucket refill accurately with Lua?", "Hard", "Senior Engineer", "Patterns", "04-distributed-systems/lua-scripts.md"),
    (147, "What are the tradeoffs of caching entire DTOs versus hash field projections?", "Medium", "Lead", "Patterns", "02-core-redis/hashes.md"),
    (148, "How do you prevent double consumption when a consumer crashes before XACK?", "Hard", "Lead", "Patterns", "04-distributed-systems/streams.md"),
    (149, "When does Redis Pub/Sub suffice for feature-flag propagation versus polling?", "Easy", "Senior Engineer", "Patterns", "04-distributed-systems/pub-sub.md"),
    (150, "How would you design negative caching TTL differently for bots versus real users?", "Hard", "Lead", "Patterns", "05-production-patterns/cache-penetration.md"),
]
